#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${M_MANGOSD}" != "true" ]]; then
	exit 0
fi

# Useful sql functions
function rootSQL {
	QUERY="${@}"
	mysql -h "${SQL_HOSTNAME}" -P "${SQL_PORT}" -u "root" "-p${MYSQL_ROOT_PASSWORD}" -BNe "${QUERY}"
}

DB_CONFIG=(
	'LoginDatabaseInfo'
	'CharacterDatabaseInfo'
	'WorldDatabaseInfo'
)

if [[ -z "${MYSQL_ROOT_PASSWORD}" ]]; then
	echo "[***] MySQL root password was not supplied. Assuming SQL credentials are valid and database was created."
else
	# Ensure DBs exist and user can be created
	for CONFIG_KEY in ${DB_CONFIG[@]}; do
		SQL_CONFIG=$(awk "/^${CONFIG_KEY}/{print \$NF}" "/config/${M_MANGOSD_CONFIGFILE}")
		regex="^\"([^;]+);([^;]+);([^;]+);([^;]+);([^;]+)\""
		if [[ ${SQL_CONFIG} =~ $regex ]]; then
			SQL_HOSTNAME=${BASH_REMATCH[1]}
			SQL_PORT=${BASH_REMATCH[2]}
			SQL_USER=${BASH_REMATCH[3]}
			SQL_PASSWORD=${BASH_REMATCH[4]}
			SQL_DB=${BASH_REMATCH[5]}

			# Wait for 10 minutes for SQL to come up
			echo "[***] Waiting for SQL server to come up."
			timeout 600 sh -c 'until nc -z $0 $1; do sleep 1; done' "${SQL_HOSTNAME}" "${SQL_PORT}"
			if [[ $? -ne 0 ]]; then
				echo "[***] ERROR: MySQL Server did not respond within 10 minutes."
				exit 1
			fi
			echo "[***] MySQL is up (${CONFIG_KEY})"
			sleep 5s

			# Create auth database per settings file
			rootSQL "CREATE DATABASE IF NOT EXISTS \`${SQL_DB}\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
			# Create user credentials per settings file
			rootSQL "CREATE USER IF NOT EXISTS '${SQL_USER}'@'%' IDENTIFIED BY '${SQL_PASSWORD}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;"
			# Grant user usage from any source
			rootSQL "GRANT USAGE ON *.* TO '${SQL_USER}'@'%';"
			# Grant privileges of user to database
			rootSQL "GRANT ALL PRIVILEGES ON \`${SQL_DB}\`.* TO '${SQL_USER}'@'%' WITH GRANT OPTION;"
		else
			echo "[***] ERROR: Somehow ${CONFIG_KEY} in '/config/${M_MANGOSD_CONFIGFILE}' was not formatted as 'hostname;port;user;password;database'."
			exit 1
		fi

	done
fi

