#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${AC_WORLDSERVER}" != "true" ]]; then
        exit 0
fi

if [[ ! -d /wow || ! -d /wow/Data ]]; then
	echo "[***] WoW folder not detected at /wow. Skipping preparing any maps, vmaps, mmaps."
	echo "[***] This is not an issue if you've already loaded anything you need into the /config volume."
	exit 0
fi

if [[ ! -d /config/dbc || ! -d /config/maps ]]; then
	echo "[***] DBC and Maps: generating files"
	cd /wow
	/ac/bin/mapextractor
	cp -r dbc maps /config
	echo "[***] DBC and Maps: complete"
fi

if [[ ! -d /config/vmaps ]]; then
	echo "[***] Visual maps: generating files"
	cd /wow
	/ac/bin/vmap4extractor
	mkdir vmaps
	/ac/bin/vmap4assembler Buildings vmaps
	cp -r vmaps /config
	echo "[***] Visual maps: complete"
fi

if [[ ! -d /config/mmaps ]]; then
	echo "[***] Movement maps: generating files"
	cd /wow
	/ac/bin/mmaps_generator
	cp -r mmaps /config
	echo "[***] Movement maps: complete"
fi

# Cleanup
for x in 'dbc' 'maps' 'vmaps' 'mmaps'; do
	if [[ -d /wow/${x} ]]; then
		echo "[***] Cleaning up ${x} from /wow folder"
		rm -R /wow/${x}
	fi
done
