#!/usr/bin/with-contenv bash

if [[ "${AC_AUTHSERVER}" == "true" ]]; then
	echo "[***] AUTHSERVER is enabled"
	if [[ -e /etc/services.d/authserver/down ]]; then
		rm /etc/services.d/authserver/down
	fi
	if [[ ! -e "/config/${AC_AUTHSERVER_CONFIGFILE}" ]]; then
		cp /ac/etc/authserver.conf.dist "/config/${AC_AUTHSERVER_CONFIGFILE}"
	fi
else
	touch /etc/services.d/authserver/down
fi

if [[ "${AC_WORLDSERVER}" == "true" ]]; then
	echo "[***] WORLDSERVER is enabled"
	if [[ -e /etc/services.d/worldserver/down ]]; then
		rm /etc/services.d/worldserver/down
	fi
	if [[ ! -e "/config/${AC_WORLDSERVER_CONFIGFILE}" ]]; then
		cp /ac/etc/worldserver.conf.dist "/config/${AC_WORLDSERVER_CONFIGFILE}"
	fi
else
	touch /etc/services.d/worldserver/down
fi

for x in "/config/${AC_AUTHSERVER_CONFIGFILE}" "/config/${AC_WORLDSERVER_CONFIGFILE}"; do
	if [[ -e ${x} ]]; then
		sed -i 's#^SourceDirectory .*#SourceDirectory = "/AshamaneCore"#g' ${x}
	fi
done
