#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${AC_WORLDSERVER}" != "true" ]]; then
	exit 0
fi

if [[ -z "${MYSQL_ROOT_PASSWORD}" ]]; then
	echo "[***] MySQL root password was not supplied. Assuming authserver SQL credentials are valid and database was already created."
	exit 0
fi

source /gowowcore/_sql.sh

DB_CONFIG=(
	'LoginDatabaseInfo'
	'CharacterDatabaseInfo'
	'WorldDatabaseInfo'
)

for CONFIG_KEY in ${DB_CONFIG[@]}; do
	SQLextractCreds "${CONFIG_KEY}" "/config/${AC_WORLDSERVER_CONFIGFILE}"

	SQLwaitPort

	# Create user credentials per settings file
	SQLroot "CREATE USER IF NOT EXISTS '${SQL_USER}'@'%' IDENTIFIED BY '${SQL_PASSWORD}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;"
	# Grant user usage from any source
	SQLroot "GRANT USAGE ON *.* TO '${SQL_USER}'@'%';"

	# Create auth database per settings file
	SQLroot "CREATE DATABASE IF NOT EXISTS \`${SQL_DB}\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
	# Grant privileges of user to database
	SQLroot "GRANT ALL PRIVILEGES ON \`${SQL_DB}\`.* TO '${SQL_USER}'@'%' WITH GRANT OPTION;"
done
