#!/usr/bin/with-contenv bash
# Exit if authserver is not enabled
if [[ "${AC_AUTHSERVER}" != "true" ]]; then
	exit 0
fi

(
	source /gowowcore/_sql.sh
	SQLextractCreds "LoginDatabaseInfo" "/config/${AC_AUTHSERVER_CONFIGFILE}"
	SQLwaitPort

	for table in 'account' 'rbac_account_permissions' 'realmlist'; do
		SQLwaitTable "${table}"
	done

	# Autogenerate initial admin user
	SQLuser "INSERT IGNORE INTO \`account\` (\`id\`,\`username\`,\`sha_pass_hash\`,\`expansion\`) VALUES ( 1, 'admin', SHA1(CONCAT(UPPER('admin'), ':', UPPER('admin'))), 2);"
	SQLuser "INSERT IGNORE INTO \`rbac_account_permissions\` (\`accountId\`, \`permissionId\`, \`granted\`, \`realmId\`) VALUES (1, 3, 1, -1);"

	# Purge default "Trinity" realm
	SQLuser "DELETE FROM \`realmlist\` WHERE \`id\`=1 AND \`name\`='Trinity' AND \`address\`='127.0.0.1' AND \`localAddress\`='127.0.0.1' AND \`localSubnetMask\`='255.255.255.0' AND \`port\`=8085;"
) &
