#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${AC_WORLDSERVER}" != "true" ]]; then
	exit 0
fi

source /gowowcore/_sql.sh

SQLextractCreds "LoginDatabaseInfo" "/config/${AC_WORLDSERVER_CONFIGFILE}"
SQLwaitPort
SQLwaitUser

SQLwaitTable 'realmlist'

if [[ -z "${AC_WORLDSERVER_REALMID}" ]]; then
	AC_WORLDSERVER_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${AC_WORLDSERVER_NAME}';")
fi
if [[ -n "${AC_WORLDSERVER_REALMID}" ]]; then
	SQLuser "REPLACE INTO \`realmlist\` (\`id\`,\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`gamebuild\`) VALUES (${AC_WORLDSERVER_REALMID}, '${AC_WORLDSERVER_NAME}', '${AC_WORLDSERVER_ADDRESS}', ${AC_WORLDSERVER_PORT}, ${AC_WORLDSERVER_ICON}, ${AC_WORLDSERVER_TZ}, ${AC_WORLDSERVER_MINSECURITY}, ${AC_WORLDSERVER_GAMEBUILD});"
else
	SQLuser "REPLACE INTO \`realmlist\` (\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`gamebuild\`) VALUES ('${AC_WORLDSERVER_NAME}','${AC_WORLDSERVER_ADDRESS}', ${AC_WORLDSERVER_PORT}, ${AC_WORLDSERVER_ICON}, ${AC_WORLDSERVER_TZ}, ${AC_WORLDSERVER_MINSECURITY}, ${AC_WORLDSERVER_GAMEBUILD});"
fi

AC_WORLDSERVER_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${AC_WORLDSERVER_NAME}';")

sed -i "s/^RealmID .*/RealmID = ${AC_WORLDSERVER_REALMID}/g" "/config/${AC_WORLDSERVER_CONFIGFILE}"
