os: linux
dist: focal
language: shell
services:
- docker
addons:
  apt:
    update: true
    sources:
    - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - git

env:
# TrinityCore family
- PAYLOAD=3.3.5a-trinitycore
- PAYLOAD=3.3.5a-trinitycore-spp

# Standard MaNGOS family
- PAYLOAD=1.12.1-mangos-zero
- PAYLOAD=2.4.3-mangos-one
- PAYLOAD=3.3.5a-mangos-two
- PAYLOAD=4.3.4-mangos-three
- PAYLOAD=5.4.8-mangos-four

# MaNGOS with PLAYERBOTS enabled
- PAYLOAD=1.12.1-mangos-zero-playerbots
- PAYLOAD=2.4.3-mangos-one-playerbots
- PAYLOAD=3.3.5a-mangos-two-playerbots
- PAYLOAD=4.3.4-mangos-three-playerbots
- PAYLOAD=5.4.8-mangos-four-playerbots

script:
- cd ${PAYLOAD}
- docker-compose build
