os: linux
dist: focal
language: shell

git:
  depth: 1
  quiet: true

services:
- docker

addons:
  apt:
    update: true
    sources:
    - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - git

#before_install:
#- sudo rm /usr/local/bin/docker-compose
#- curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-`uname -s`-`uname -m` > docker-compose
#- chmod +x docker-compose
#- sudo mv docker-compose /usr/local/bin

script:
- cd ${PAYLOAD}
- docker login docker.pkg.github.com -u "${GITHUB_USER}" -p "${GITHUB_TOKEN}" &> /dev/null
- docker-compose -f docker-compose-ci.yml build
- if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "base" ]]; then docker-compose -f docker-compose-ci.yml push ; fi

stages:
- base
- packs

jobs:
  include:
  - env: PAYLOAD=base
    stage: base

  - env: PAYLOAD=1.12.1-mangos-zero
    stage: packs
  - env: PAYLOAD=1.12.1-mangos-zero-playerbots

  - env: PAYLOAD=2.4.3-mangos-one
  - env: PAYLOAD=2.4.3-mangos-one-playerbots

  - env: PAYLOAD=3.3.5a-azerothcore
  - env: PAYLOAD=3.3.5a-mangos-two
  - env: PAYLOAD=3.3.5a-mangos-two-playerbots
  - env: PAYLOAD=3.3.5a-trinitycore
  - env: PAYLOAD=3.3.5a-trinitycore-spp

  - env: PAYLOAD=4.3.4-mangos-three
  - env: PAYLOAD=4.3.4-mangos-three-playerbots
  - env: PAYLOAD=4.3.4-trinitycore-cata

  - env: PAYLOAD=5.4.8-mangos-four
  - env: PAYLOAD=5.4.8-mangos-four-playerbots
