#!/usr/bin/with-contenv bash
if [[ "${CORE}" != "mangos" ]]; then
	exit 0
fi
if [[ "${WORLDSERVER}" != "true" ]]; then
	exit 0
fi

source /gowowcore/_conf.sh

## SQL Configs
sql_regex="^mysql://([^:]+):([^@]+)@([^:]+):([^/]+)/(.*)$"
entries=(
	'LoginDatabaseInfo,AUTH_SQL'
	'CharacterDatabaseInfo,CHARACTER_SQL'
	'WorldDatabaseInfo,WORLD_SQL'
)
for entry in ${entries[@]}; do
	CONF_PARAM=${entry%,*}
	CONF_ENV=${entry#*,}
	if [[ ${!CONF_ENV} =~ $sql_regex ]]; then
		SQL_HOSTNAME=${BASH_REMATCH[3]}
		SQL_PORT=${BASH_REMATCH[4]}
		SQL_USER=${BASH_REMATCH[1]}
		SQL_PASSWORD=${BASH_REMATCH[2]}
		SQL_DB=${BASH_REMATCH[5]}
		CONFsetQuoted "/config/${WORLDSERVER_CONFIGFILE}" "${CONF_PARAM}" "${SQL_HOSTNAME};${SQL_PORT};${SQL_USER};${SQL_PASSWORD};${SQL_DB}"
	else
		echo "[***] ERROR: ${!CONF_ENV} format is invalid. Should be 'mysql://user:password@hostname:port/database_name'"
	fi
done


# Raw configs
entries=(
	'WorldServerPort,WORLDSERVER_PORT'
	'SOAP.Port,WORLDSERVER_SOAP_PORT'
	'RealmID,WORLDSERVER_REALMID'
	'GameType,WORLDSERVER_ICON'
	'RealmZone,WORLDSERVER_TZ'
)
for entry in ${entries[@]}; do
	CONF_PARAM=${entry%,*}
	CONF_ENV=${entry#*,}
	if [[ -n "${!CONF_ENV}" ]]; then
		CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "${CONF_PARAM}" "${!CONF_ENV}"
	fi
done

# Quoted configs
# Don't override IP Bindings, let user do via config file directly
#entries=(
#	'BindIP,WORLDSERVER_ADDRESS'
#	'SOAP.IP,WORLDSERVER_SOAP_ADDRESS'
#)
#for entry in ${entries[@]}; do
#	CONF_PARAM=${entry%,*}
#	CONF_ENV=${entry#*,}
#	if [[ -n "${!CONF_ENV}" ]]; then
#		CONFsetQuoted "/config/${WORLDSERVER_CONFIGFILE}" "${CONF_PARAM}" "${!CONF_ENV}"
#	fi
#done

if [[ "${WORLDSERVER_SOAP}" == "true" ]]; then
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "SOAP.Enabled" "1"
else
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "SOAP.Enabled" "0"
fi

# mmap/vmap/etc stuff
for folder in 'dbc' 'maps' 'mmaps' 'vmaps'; do
	if [[ -e /app/etc/${folder} ]]; then
		rm /app/etc/${folder}
	fi
	if [[ -d /config/${folder} ]]; then
		ln -s "/config/${folder}" "/app/etc/${folder}"
	fi
done

if [[ -d /config/mmaps ]]; then
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "mmap.enablePathFinding" "1"
else
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "mmap.enablePathFinding" "0"
fi

if [[ -d /config/vmaps ]]; then
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "vmap.enableLOS" "1"
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "vmap.enableHeight" "1"
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "vmap.enableIndoorCheck" "1"
else
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "vmap.enableLOS" "0"
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "vmap.enableHeight" "0"
	CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "vmap.enableIndoorCheck" "0"
fi
