#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${WORLDSERVER}" != "true" ]]; then
	exit 0
fi

source /gowowcore/_sql.sh
source /gowowcore/_conf.sh

# Trinitycore is configured to handle DB installation/updates directly

SQLextractCreds "CharacterDatabaseInfo" "/config/${WORLDSERVER_CONFIGFILE}"
SQLwaitPort
SQLwaitUser

# Install characterDB

if [[ -e /src/db/Character/Setup/characterLoadDB.sql ]]; then
	# Mangos
	# Install DB if version table is missing
	if [[ $(SQLuser "SHOW TABLES LIKE 'db_version';" | wc -l) -eq 0 ]]; then
		echo "[***] Couldn't find db_version table in ${SQL_DB}. Installing CharacterDatabaseInfo to ${SQL_DB}."
		SQLuserFile "/src/db/Character/Setup/characterLoadDB.sql"
	fi
	# Get DB version
	DB_VERSION=$(SQLuser "SELECT \`version\` FROM \`db_version\` ORDER BY \`version\` DESC, \`structure\` DESC LIMIT 0,1;")
	echo "[***] CharacterDatabaseInfo installed is ${DB_VERSION}"
	
elif [[ -d /src/server/data/sql/base/db_characters ]]; then
	# azerothcore
	for table_sql in $(ls -1 "/src/server/data/sql/base/db_characters/"); do
		table=${table_sql%.*}
		if ! SQLexistTable "${table}"; then
			SQLuserFile "/src/server/data/sql/base/db_characters/${table_sql}"
		fi
	done
fi


# Initiate relevant migrations
if [[ -n "${DB_VERSION}" && -d "/src/db/Character/Updates/Rel${DB_VERSION}" ]]; then
	# Mangos
	echo "[***] Running all available Character DB updates"
	for x in $(ls -1 /src/db/Character/Updates/Rel${DB_VERSION}/*.sql | sort -n); do
		sed -i 's#DEFINER=`root`@`localhost`##g' "${x}"
		SQLuserFile "${x}"
	done
elif [[ -d /src/server/data/sql/updates/db_characters ]]; then
	# azerothcore
	echo "[***] Running all available Character DB updates"
	for migration_sql in $(ls -1 "/src/server/data/sql/updates/db_characters/"); do
		SQLuserFile "/src/server/data/sql/updates/db_characters/${migration_sql}"
	done

fi
