#!/usr/bin/with-contenv bash
if [[ "${CORE}" != "mangos" ]]; then
	exit 0
fi
# Exit if worldserver is not enabled
if [[ "${WORLDSERVER}" != "true" ]]; then
	exit 0
fi

source /gowowcore/_sql.sh
source /gowowcore/_conf.sh

# Install Character and World DBs
for entry in 'World,WorldDatabaseInfo,db/World/Setup/mangosdLoadDB.sql' 'Character,CharacterDatabaseInfo,db/Character/Setup/characterLoadDB.sql'; do
	FOLDER=$(echo ${entry} | cut -d',' -f1)
	CONFIG_ATTR=$(echo ${entry} | cut -d',' -f2)
	SQL_FILE=$(echo ${entry} | cut -d',' -f3)

	SQLextractCreds "${CONFIG_ATTR}" "/config/${WORLDSERVER_CONFIGFILE}"
	SQLwaitPort
	SQLwaitUser

	# Install DB if not exists
	if [[ $(SQLuser "SHOW TABLES LIKE 'db_version';" | wc -l) -eq 0 ]]; then
		echo "[***] Couldn't find db_version table in ${SQL_DB}. Installing ${CONFIG_ATTR} to ${SQL_DB}."
		SQLuserFile "/src/${SQL_FILE}"
		if [[ "${CONFIG_ATTR}" == "WorldDatabaseInfo" ]]; then
			for x in $(ls -1 /src/db/World/Setup/FullDB/*.sql); do
				SQLuserFile "${x}"
			done
		fi
	fi
	DB_VERSION=$(SQLuser "SELECT \`version\` FROM \`db_version\` ORDER BY \`version\` DESC, \`structure\` DESC LIMIT 0,1;")
	echo "[***] ${CONFIG_ATTR} installed is ${DB_VERSION}"
	# Run all upgrade queries from /Updates/Rel-version
	echo "[***] Running all available DB migrations"
	for x in $(ls -1 /src/db/${FOLDER}/Updates/Rel${DB_VERSION}/*.sql | sort -n); do
		sed -i 's#DEFINER=`root`@`localhost`##g' "${x}"
		SQLuserFile "${x}"
	done
done

# Register with realmlist in authDB
SQLextractCreds "LoginDatabaseInfo" "/config/${WORLDSERVER_CONFIGFILE}"
SQLwaitPort
SQLwaitUser

SQLwaitTable "realmlist"

# Sync this realm into the realmlist
if [[ -z "${WORLDSERVER_REALMID}" ]]; then
	WORLDSERVER_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${WORLDSERVER_NAME}';")
fi
if [[ -n "${WORLDSERVER_REALMID}" ]]; then
	SQLuser "REPLACE INTO \`realmlist\` (\`id\`,\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`realmbuilds\`) VALUES (${WORLDSERVER_REALMID}, '${WORLDSERVER_NAME}', '${WORLDSERVER_ADDRESS}', ${WORLDSERVER_PORT}, ${WORLDSERVER_ICON}, ${WORLDSERVER_TZ}, ${WORLDSERVER_MINSECURITY}, ${WORLDSERVER_REALMBUILD});"
else
	SQLuser "REPLACE INTO \`realmlist\` (\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`realmbuilds\`) VALUES ('${WORLDSERVER_NAME}','${WORLDSERVER_ADDRESS}', ${WORLDSERVER_PORT}, ${WORLDSERVER_ICON}, ${WORLDSERVER_TZ}, ${WORLDSERVER_MINSECURITY}, ${WORLDSERVER_REALMBUILD});"
fi

WORLDSERVER_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${WORLDSERVER_NAME}';")
CONFsetRaw "/config/${WORLDSERVER_CONFIGFILE}" "RealmID" "${WORLDSERVER_REALMID}"
