#!/usr/bin/with-contenv bash
# Exit if authserver is not enabled
if [[ "${TC_AUTHSERVER}" != "true" ]]; then
	exit 0
fi

# Useful sql functions
function rootSQL {
	QUERY="${@}"
	mysql -h "${SQL_HOSTNAME}" -P "${SQL_PORT}" -u "root" "-p${MYSQL_ROOT_PASSWORD}" -BNe "${QUERY}"
}

# Wait for SQL to come up and pre-create the database and user if we need to
if [[ -z "${MYSQL_ROOT_PASSWORD}" ]]; then
	echo "[***] MySQL root password was not supplied. Assuming authserver SQL credentials are valid and database was created."
else
	# Handle necessary SQL DB and User creation
	SQL_CONFIG=$(awk '/^LoginDatabaseInfo/{print $NF}' "/config/${TC_AUTHSERVER_CONFIGFILE}")
	regex="^\"([^;]+);([^;]+);([^;]+);([^;]+);([^;]+)\""
	if [[ ${SQL_CONFIG} =~ $regex ]]; then
		SQL_HOSTNAME=${BASH_REMATCH[1]}
		SQL_PORT=${BASH_REMATCH[2]}
		SQL_USER=${BASH_REMATCH[3]}
		SQL_PASSWORD=${BASH_REMATCH[4]}
		SQL_DB=${BASH_REMATCH[5]}

		# Wait for 10 minutes for SQL to come up
		echo "[***] Waiting for SQL server to come up."
		timeout 600 sh -c 'until nc -z $0 $1; do sleep 1; done' "${SQL_HOSTNAME}" "${SQL_PORT}"
		if [[ $? -ne 0 ]]; then
			echo "[***] ERROR: MySQL Server did not respond within 10 minutes."
			exit 1
		fi
		echo "[***] MySQL is up"
		sleep 5s

		# Create auth database per settings file
		rootSQL "CREATE DATABASE IF NOT EXISTS \`${SQL_DB}\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
		# Create user credentials per settings file
		rootSQL "CREATE USER IF NOT EXISTS '${SQL_USER}'@'%' IDENTIFIED BY '${SQL_PASSWORD}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;"
		# Grant user usage from any source
		rootSQL "GRANT USAGE ON *.* TO '${SQL_USER}'@'%';"
		# Grant privileges of user to database
		rootSQL "GRANT ALL PRIVILEGES ON \`${SQL_DB}\`.* TO '${SQL_USER}'@'%' WITH GRANT OPTION;"
	else
		echo "[***] ERROR: Somehow LoginDatabaseInfo in '/config/${TC_AUTHSERVER_CONFIGFILE}' was not formatted as 'hostname;port;user;password;database'."
		exit 1
	fi
fi
