#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${TC_WORLDSERVER}" != "true" ]]; then
	exit 0
fi

source /gowowcore/_sql.sh

SQLextractCreds "LoginDatabaseInfo" "/config/${TC_WORLDSERVER_CONFIGFILE}"
SQLwaitPort
SQLwaitUser

SQLwaitTable 'realmlist'

if [[ -z "${TC_WORLDSERVER_REALMID}" ]]; then
	TC_WORLDSERVER_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${TC_WORLDSERVER_NAME}';")
fi
if [[ -n "${TC_WORLDSERVER_REALMID}" ]]; then
	SQLuser "REPLACE INTO \`realmlist\` (\`id\`,\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`gamebuild\`) VALUES (${TC_WORLDSERVER_REALMID}, '${TC_WORLDSERVER_NAME}', '${TC_WORLDSERVER_ADDRESS}', ${TC_WORLDSERVER_PORT}, ${TC_WORLDSERVER_ICON}, ${TC_WORLDSERVER_TZ}, ${TC_WORLDSERVER_MINSECURITY}, ${TC_WORLDSERVER_GAMEBUILD});"
else
	SQLuser "REPLACE INTO \`realmlist\` (\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`gamebuild\`) VALUES ('${TC_WORLDSERVER_NAME}','${TC_WORLDSERVER_ADDRESS}', ${TC_WORLDSERVER_PORT}, ${TC_WORLDSERVER_ICON}, ${TC_WORLDSERVER_TZ}, ${TC_WORLDSERVER_MINSECURITY}, ${TC_WORLDSERVER_GAMEBUILD});"
fi

TC_WORLDSERVER_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${TC_WORLDSERVER_NAME}';")

sed -i "s/^RealmID .*/RealmID = ${TC_WORLDSERVER_REALMID}/g" "/config/${TC_WORLDSERVER_CONFIGFILE}"
