#!/usr/bin/with-contenv bash
# Exit if authserver is not enabled
if [[ "${TC_AUTHSERVER}" != "true" ]]; then
	exit 0
fi

(
	function userSQL {
		QUERY="${@}"
		mysql -h "${SQL_HOSTNAME}" -P "${SQL_PORT}" -u "${SQL_USER}" "-p${SQL_PASSWORD}" "${SQL_DB}" -BNe "${QUERY}"
	}
	# Wait for authserver to start responding
	while ! nc -z localhost ${TC_AUTHSERVER_PORT}; do
		sleep 1s
	done

	# Reload SQL config(I don't think this inherits)
	SQL_CONFIG=$(awk '/^LoginDatabaseInfo/{print $NF}' "/config/${TC_AUTHSERVER_CONFIGFILE}")
	regex="^\"([^;]+);([^;]+);([^;]+);([^;]+);([^;]+)\""
	if [[ ${SQL_CONFIG} =~ $regex ]]; then
		SQL_HOSTNAME=${BASH_REMATCH[1]}
		SQL_PORT=${BASH_REMATCH[2]}
		SQL_USER=${BASH_REMATCH[3]}
		SQL_PASSWORD=${BASH_REMATCH[4]}
		SQL_DB=${BASH_REMATCH[5]}
	else
		echo "[***] That was weird, couldn't get SQL credentials from authserver config file. I had it before."
		exit 1
	fi
	
	# Wait for tables to be created
	for table in 'account' 'rbac_account_permissions' 'realmlist'; do
		while [[ $(userSQL "SHOW TABLES LIKE '${table}';" | wc -l) -eq 0 ]]; do
			sleep 1s
		done
	done
	
	## INSERT INTO account (`username`,`sha_pass_hash`,`expansion`) VALUES ('admin',SHA1(CONCAT(UPPER('admin'),':',UPPER('admin'))),2);
	## INSERT INTO rbac_account_permissions (`accountId`, `permissionId`, `granted`, `realmId`) VALUES (1, 3, 1, -1);
	# Autogenerate initial admin user
	userSQL "INSERT IGNORE INTO \`account\` (\`id\`,\`username\`,\`sha_pass_hash\`,\`expansion\`) VALUES ( 1, 'admin', SHA1(CONCAT(UPPER('admin'), ':', UPPER('admin'))), 2);"
	userSQL "INSERT IGNORE INTO \`rbac_account_permissions\` (\`accountId\`, \`permissionId\`, \`granted\`, \`realmId\`) VALUES (1, 3, 1, -1);"

	# Purge default "Trinity" realm
	userSQL "DELETE FROM \`realmlist\` WHERE \`id\`=1 AND \`name\`='Trinity' AND \`address\`='127.0.0.1' AND \`localAddress\`='127.0.0.1' AND \`localSubnetMask\`='255.255.255.0' AND \`port\`=8085;"
) &
