#!/usr/bin/with-contenv bash
if [[ "${CORE}" != "mangos" ]]; then
	exit 0
fi

if [[ "${AUTHSERVER}" == "true" ]]; then
	echo "[***] REALMD is enabled"
	if [[ -e /etc/services.d/authserver/down ]]; then
		rm /etc/services.d/authserver/down
	fi
	if [[ ! -e "/config/${AUTHSERVER_CONFIGFILE}" ]]; then
		cp /app/etc/realmd.conf.dist "/config/${AUTHSERVER_CONFIGFILE}"
	fi
else
	touch /etc/services.d/authserver/down
fi

if [[ "${WORLDSERVER}" == "true" ]]; then
	echo "[***] MANGOSD is enabled"
	if [[ -e /etc/services.d/worldserver/down ]]; then
		rm /etc/services.d/worldserver/down
	fi
	if [[ ! -e "/config/${WORLDSERVER_CONFIGFILE}" ]]; then
		cp /app/etc/mangosd.conf.dist "/config/${WORLDSERVER_CONFIGFILE}"
	fi
	if [[ ! -e "/config/${WORLDSERVER_AH_CONFIGFILE}" ]]; then
		cp /app/etc/ahbot.conf.dist "/config/${WORLDSERVER_AH_CONFIGFILE}"
	fi
else
	touch /etc/services.d/worldserver/down
fi
