#!/usr/bin/with-contenv bash
if [[ "${CORE}" != "trinitycore" ]]; then
	exit 0
fi

source /gowowcore/_conf.sh

if [[ "${AUTHSERVER}" == "true" ]]; then
	echo "[***] AUTHSERVER is enabled"
	if [[ -e /etc/services.d/authserver/down ]]; then
		rm /etc/services.d/authserver/down
	fi
	if [[ ! -e "/config/${AUTHSERVER_CONFIGFILE}" ]]; then
		cp /app/etc/authserver.conf.dist "/config/${AUTHSERVER_CONFIGFILE}"
	fi
else
	touch /etc/services.d/authserver/down
fi

if [[ "${WORLDSERVER}" == "true" ]]; then
	echo "[***] WORLDSERVER is enabled"
	if [[ -e /etc/services.d/worldserver/down ]]; then
		rm /etc/services.d/worldserver/down
	fi
	if [[ ! -e "/config/${WORLDSERVER_CONFIGFILE}" ]]; then
		cp /app/etc/worldserver.conf.dist "/config/${WORLDSERVER_CONFIGFILE}"
	fi
else
	touch /etc/services.d/worldserver/down
fi

for x in "/config/${AUTHSERVER_CONFIGFILE}" "/config/${WORLDSERVER_CONFIGFILE}"; do
	if [[ -e "${x}" ]]; then
		CONFsetQuoted "${x}" "SourceDirectory" "/src/server"
	fi
done
