#!/usr/bin/with-contenv bash
for x in '/run/nginx' '/config/nginx' '/config/nginx/log'; do
	if [[ ! -d ${x} ]]; then
		mkdir ${x}
		chown nginx:nginx ${x}
	fi
done
sed -i 's@/var/log/nginx/@/config/nginx/log/@g' /etc/nginx/nginx.conf
sed -i 's@user nginx;@user abc;@g' /etc/nginx/nginx.conf
cat > /etc/nginx/conf.d/default.conf <<-EOF
server {
  listen ${PORT:-80};
  root /app;
  index index.php index.html index.htm;
  server_name _;
  location / {
    try_files \$uri \$uri/ /index.php?\$request_uri;
  }
  location ~ \.php$ {
    fastcgi_pass unix:/var/run/php-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    include fastcgi_params;
  }

}
EOF
