version: '2.1'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-insecurepassword}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_INITDB_SKIP_TZINFO: "1"
    ports:
    - "3306:3306"
    volumes:
    - "./mariadb:/var/lib/mysql"

  realmd:
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        MANGOS_FAMILY: zero
    image: "mangoszero-realmd-1.12.1:latest"
    restart: always
    depends_on:
    - db
    ports:
    - "3724:3724"
    volumes:
    - "./config.realmd:/config"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-insecurepassword}"

      M_REALMD: "true"
      M_AUTH_SQL: mysql://mangos:mangos@db:3306/auth
      M_REALMD_PORT: "3724"

  mangosd:
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        MANGOS_FAMILY: zero
    image: "mangoszero-mangosd-1.12.1:latest"
    restart: always
    depends_on:
    - db
    ports:
    - "8085:8085"
    - "7878:7878"
    volumes:
    - "./config.mangosd:/config"
    - "./wow-1.12.1:/wow"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-insecurepassword}"

      M_MANGOSD: "true"
      M_MANGOSD_SOAP: "true"
      M_MANGOSD_SOAP_PORT: "7878"

      M_AUTH_SQL: mysql://mangos:mangos@db:3306/auth
      M_CHARACTER_SQL: mysql://mangos:mangos@db:3306/characters
      M_WORLD_SQL: mysql://mangos:mangos@db:3306/world

      # IF realmid is defined, will override existing realm of this id(if exists), otherwise will update based on NAME and will update config file accordingly
      M_MANGOSD_REALMID: 1
      M_MANGOSD_NAME: "GoWowCore_mangoszero-1.12.1_1"
      M_MANGOSD_ADDRESS: "127.0.0.1"
      M_MANGOSD_PORT: "8085"
      M_MANGOSD_ICON: "0"
      M_MANGOSD_TZ: "1"
      M_MANGOSD_MINSECURITY: "0"

  mangosd2:
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        MANGOS_FAMILY: zero
    image: "mangoszero-mangosd-1.12.1:latest"
    restart: always
    depends_on:
    - db
    ports:
    - "8086:8086"
    - "7879:7879"
    volumes:
    - "./config.mangosd:/config"
#    - "./wow-1.12.1:/wow"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-insecurepassword}"
      M_MANGOSD_CONFIGFILE: "mangosd2.conf"

      M_MANGOSD: "true"
      M_MANGOSD_SOAP: "true"
      M_MANGOSD_SOAP_PORT: "7879"

      M_AUTH_SQL: mysql://mangos:mangos@db:3306/auth
      M_CHARACTER_SQL: mysql://mangos:mangos@db:3306/characters2
      M_WORLD_SQL: mysql://mangos:mangos@db:3306/world2

      # IF realmid is defined, will override existing realm of this id(if exists), otherwise will update based on NAME and will update config file accordingly
#      M_MANGOSD_REALMID: 2
      M_MANGOSD_NAME: "GoWowCore_mangoszero-1.12.1_2"
      M_MANGOSD_ADDRESS: "127.0.0.1"
      M_MANGOSD_PORT: "8086"
      M_MANGOSD_ICON: "0"
      M_MANGOSD_TZ: "1"
      M_MANGOSD_MINSECURITY: "0"
