version: '2.1'

services:
  build:
    build:
      context: "."
      dockerfile: Dockerfile.build
    image: ghcr.io/gowowcore/base-build:latest
  prod:
    build:
      context: "."
      dockerfile: Dockerfile.prod
    image: ghcr.io/gowowcore/base-prod:latest
