#!/usr/bin/with-contenv bash
cd /app/bin
BINARY=""
CFG=""
if [[ -x /app/bin/authserver ]]; then
	BINARY="/app/bin/authserver"
	CFG="/app/etc/authserver.conf"
elif [[ -x /app/bin/realmd ]]; then
	BINARY="/app/bin/realmd"
	CFG="/app/etc/realmd.conf"
fi

if [[ -z "${BINARY}" || -z "${CFG}" ]]; then
	exit 1
fi

exec \
	/usr/bin/screen -D -m -S AUTHSERVER s6-setuidgid abc "${BINARY}" -c "${CFG}"
