#!/usr/bin/with-contenv bash
# Exit if worldserver is not enabled
if [[ "${M_MANGOSD}" != "true" ]]; then
	exit 0
fi

source /gowowcore/_sql.sh

# Install Character and World DBs
for entry in 'World,WorldDatabaseInfo,db/World/Setup/mangosdLoadDB.sql' 'Character,CharacterDatabaseInfo,db/Character/Setup/characterLoadDB.sql'; do
	FOLDER=$(echo ${entry} | cut -d',' -f1)
	CONFIG_ATTR=$(echo ${entry} | cut -d',' -f2)
	SQL_FILE=$(echo ${entry} | cut -d',' -f3)

	SQLextractCreds "${CONFIG_ATTR}" "/config/${M_MANGOSD_CONFIGFILE}"
	SQLwaitPort
	SQLwaitUser

	# Install DB if not exists
	if [[ $(SQLuser "SHOW TABLES LIKE 'db_version';" | wc -l) -eq 0 ]]; then
		echo "[***] Couldn't find db_version table in ${SQL_DB}. Installing ${CONFIG_ATTR} to ${SQL_DB}."
		SQLuserFile "/${MANGOS_FAMILY}/${SQL_FILE}"
		if [[ "${CONFIG_ATTR}" == "WorldDatabaseInfo" ]]; then
			for x in $(ls -1 /${MANGOS_FAMILY}/db/World/Setup/FullDB/*.sql); do
				SQLuserFile "${x}"
			done
		fi
	fi
	DB_VERSION=$(SQLuser "SELECT \`version\` FROM \`db_version\` ORDER BY \`version\` DESC, \`structure\` DESC LIMIT 0,1;")
	echo "[***] ${CONFIG_ATTR} installed is ${DB_VERSION}"
	# Run all upgrade queries from /Updates/Rel-version
	echo "[***] Running all available DB migrations"
	for x in $(ls -1 /${MANGOS_FAMILY}/db/${FOLDER}/Updates/Rel${DB_VERSION}/*.sql | sort -n); do
		sed -i 's#DEFINER=`root`@`localhost`##g' "${x}"
		SQLuserFile "${x}"
	done
done

# Register with realmlist in authDB
SQLextractCreds "LoginDatabaseInfo" "/config/${M_MANGOSD_CONFIGFILE}"
SQLwaitPort
SQLwaitUser

SQLwaitTable "realmlist"

# Sync this realm into the realmlist
if [[ -z "${M_MANGOSD_REALMID}" ]]; then
	M_MANGOSD_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${M_MANGOSD_NAME}';")
fi
if [[ -n "${M_MANGOSD_REALMID}" ]]; then
	SQLuser "REPLACE INTO \`realmlist\` (\`id\`,\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`realmbuilds\`) VALUES (${M_MANGOSD_REALMID}, '${M_MANGOSD_NAME}', '${M_MANGOSD_ADDRESS}', ${M_MANGOSD_PORT}, ${M_MANGOSD_ICON}, ${M_MANGOSD_TZ}, ${M_MANGOSD_MINSECURITY}, ${M_MANGOSD_REALMBUILD});"
else
	SQLuser "REPLACE INTO \`realmlist\` (\`name\`,\`address\`,\`port\`,\`icon\`,\`timezone\`,\`allowedSecurityLevel\`,\`realmbuilds\`) VALUES ('${M_MANGOSD_NAME}','${M_MANGOSD_ADDRESS}', ${M_MANGOSD_PORT}, ${M_MANGOSD_ICON}, ${M_MANGOSD_TZ}, ${M_MANGOSD_MINSECURITY}, ${M_MANGOSD_REALMBUILD});"
fi

M_MANGOSD_REALMID=$(SQLuser "SELECT \`id\` FROM \`realmlist\` WHERE \`name\`='${M_MANGOSD_NAME}';")
sed -i "s/^RealmID .*/RealmID = ${M_MANGOSD_REALMID}/g" "/config/${M_MANGOSD_CONFIGFILE}"
