#!/usr/bin/with-contenv bash
cd /app/bin
case "${CORE}" in
	"trinitycore")
		exec \
			/usr/bin/screen -D -m -S AUTHSERVER s6-setuidgid abc /app/bin/authserver -c /config/${AUTHSERVER_CONFIGFILE}
		;;
	"mangos")
		exec \
			/usr/bin/screen -D -m -S AUTHSERVER s6-setuidgid abc /app/bin/realmd -c /config/${AUTHSERVER_CONFIGFILE}
		;;
	*)
		exit 1
		;;
esac
