#!/usr/bin/with-contenv bash
if [[ "${CORE}" != "trinitycore" && "${CORE}" != "azerothcore" ]]; then
	exit 0
fi

source /gowowcore/_conf.sh

if [[ "${AUTHSERVER}" == "true" ]]; then
	echo "[***] AUTHSERVER is enabled"
	if [[ -e /etc/services.d/authserver/down ]]; then
		rm /etc/services.d/authserver/down
	fi
	if [[ ! -e "/config/${AUTHSERVER_CONFIGFILE}" ]]; then
		cp /app/etc/authserver.conf.dist "/config/${AUTHSERVER_CONFIGFILE}"
	fi
	if [[ -e /app/etc/authserver.conf ]]; then
		rm /app/etc/authserver.conf
	fi
	ln -s "/config/${AUTHSERVER_CONFIGFILE}" /app/etc/authserver.conf
else
	touch /etc/services.d/authserver/down
fi

if [[ "${WORLDSERVER}" == "true" ]]; then
	echo "[***] WORLDSERVER is enabled"
	if [[ -e /etc/services.d/worldserver/down ]]; then
		rm /etc/services.d/worldserver/down
	fi
	if [[ ! -e "/config/${WORLDSERVER_CONFIGFILE}" ]]; then
		cp /app/etc/worldserver.conf.dist "/config/${WORLDSERVER_CONFIGFILE}"
	fi
	if [[ -e /app/etc/worldserver.conf ]]; then
		rm /app/etc/worldserver.conf
	fi
	ln -s "/config/${WORLDSERVER_CONFIGFILE}" /app/etc/worldserver.conf
	# TODO: Dynamically find conf.dist files and copy them if missing, intended for azerothcore modules or other plugins
else
	touch /etc/services.d/worldserver/down
fi

# Set dir configs
for x in "/config/${AUTHSERVER_CONFIGFILE}" "/config/${WORLDSERVER_CONFIGFILE}"; do
	if [[ -e "${x}" ]]; then
		for entry in 'DataDir,/config' 'LogsDir,/config' 'SourceDirectory,/src/server'; do
			CONF_PARAM=${entry%,*}
			CONF_VALUE=${entry#*,}
			CONFsetQuoted "${x}" "${CONF_PARAM}" "${CONF_VALUE}"
		done

	fi
done

# Set logfile configs
for x in "/config/${AUTHSERVER_CONFIGFILE}" "/config/${WORLDSERVER_CONFIGFILE}"; do
        if [[ -e "${x}" ]]; then
                for entry in 'SQLDriverLogFile,SQLDriver.log'; do
                        CONF_PARAM=${entry%,*}
                        CONF_VALUE=${entry#*,}
                        PREFIX="authserver"
                        if [[ "${x}" == "/config/${WORLDSERVER_CONFIGFILE}" ]]; then
                                PREFIX="worldserver-${WORLDSERVER_NAME}"
                        fi
                        CONFsetQuoted "${x}" "${CONF_PARAM}" "${PREFIX}-${CONF_VALUE}"
                done

        fi
done

